import Link from "next/link";

export const metadata = {
  title: "Terms of Service | AI Resume Optimizer",
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12 text-gray-800">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: July 20, 2026</p>

      <h2 className="text-xl font-semibold mt-8 mb-3">1. The Service</h2>
      <p className="mb-6">
        AI Resume Optimizer ("the Service") is a tool that uses artificial intelligence to help
        users optimize their resumes for specific job applications. The Service is provided on an
        "as is" and "as available" basis.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">2. Plans & Payment</h2>
      <p className="mb-6">
        We offer a one-time "Job Search Pack" purchase and a recurring "Monthly Unlimited"
        subscription. Subscriptions renew automatically each billing period until cancelled.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">3. Refund Policy</h2>
      <ul className="list-disc pl-6 mb-6 space-y-2">
        <li>
          <strong>Job Search Pack (one-time purchase):</strong> Eligible for a full refund within
          7 days of purchase, provided the credits have not been used.
        </li>
        <li>
          <strong>Monthly Unlimited (subscription):</strong> No prorated refunds for partial
          billing periods. First-time subscribers are eligible for a full refund if requested
          within 7 days of the initial charge. You may cancel at any time to stop future renewals.
        </li>
        <li>
          To request a refund, contact{" "}
          <a href="mailto:support@yourdomain.com" className="text-blue-600 underline">
            support@yourdomain.com
          </a>
          .
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-3">4. Prohibited Use</h2>
      <ul className="list-disc pl-6 mb-6 space-y-2">
        <li>Using the Service to generate false, fraudulent, or misleading information.</li>
        <li>Reverse engineering, decompiling, or attempting to extract the source code of the Service.</li>
        <li>Using automated means (bots, scrapers) to access the Service without our permission.</li>
        <li>Reselling or redistributing outputs generated by the Service as a competing product.</li>
      </ul>

      <h2 className="text-xl font-semibold mt-8 mb-3">5. Disclaimer</h2>
      <p className="mb-6">
        The Service uses AI to generate suggestions and content. We do not guarantee the accuracy,
        completeness, or suitability of any AI-generated content for your specific purposes. You
        are solely responsible for reviewing and verifying any resume content before submitting it
        to employers.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">6. Limitation of Liability</h2>
      <p className="mb-6">
        To the maximum extent permitted by law, we are not liable for any indirect, incidental, or
        consequential damages arising from your use of the Service, including any job application
        outcomes.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">7. Governing Law</h2>
      <p className="mb-6">
        These Terms are governed by the laws of Japan. Any disputes arising from these Terms or
        the Service shall be subject to the exclusive jurisdiction of the Tokyo District Court.
      </p>

      <h2 className="text-xl font-semibold mt-8 mb-3">8. Changes to These Terms</h2>
      <p className="mb-6">
        We may update these Terms from time to time. Continued use of the Service after changes
        constitutes acceptance of the updated Terms.
      </p>

      <Link href="/" className="text-blue-600 underline">
        ← Back to home
      </Link>
    </div>
  );
}
